---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: ">=1.18.0 <=1.19.0"
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: rook-ceph
      interval: 1m
  values:
    cephClusterSpec:
      cephVersion:
        image: quay.io/ceph/ceph:v19.2.3
      dataDirHostPath: /var/lib/rook
      waitTimeoutForHeathyOSDInMinutes: 10
      mon:
        count: 3
        allowMultiplePerNode: false
      mgr:
        count: 1
        allowMultiplePerNode: false
      dashboard:
        enabled: false # We'll enable this later
        ssl: false
      crashCollector:
        disable: false
        daysToRetain: 30
      logCollector:
        enabled: true
        periodicity: daily
        maxLogSize: 20M
      resources: #TODO:  Update requests and limits in "final" cluster
        mgr:
          limits:
            memory: "1gi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        mon:
          limits:
            memory: "1gi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        osd:
          limits:
            memory: "2gi"
          requests:
            cpu: "100m"
            memory: "512Mi"
        prepareosd:
          requests:
            cpu: "100m"
            memory: "100Mi"
        mgr-sidecar:
          limits:
            memory: "100Mi"
          requests:
            cpu: "100m"
            memory: "40Mi"
        crashcollector:
          limits:
            memory: "60Mi"
          requests:
            cpu: "100m"
            memory: "60Mi"
        logcollector:
          limits:
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
        cleanup:
          limits:
            memory: "512Mi"
          requests:
            cpu: "50m"
            memory: "100Mi"
        exporter:
          limits:
            memory: "128mi"
          requests:
            cpu: "50m"
            memory: "50Mi"
      storage:
        useAllNodes: true
        useAllDevices: true
    toolbox:
      enabled: true
      resources:
        limits:
          memory: "512Mi"
        requests:
          memory: "128Mi"
    monitoring: # We'll turn this on later
      enabled: false