apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: home-apps
  namespace: flux-apps
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/nitespacedev/home-k8s-apps.git