apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-web
  namespace: rook-ceph
spec:
  path: ./storage/Rook-Ceph/web
  prune: true
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: traefik-flux
      namespace: flux-system
    - name: rook-ceph-cluster