apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-dashboard
  namespace: flux-system
spec:
  path: ./network/traefik/dashboard
  prune: true
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: traefik-flux
    - name: cert-manager
  decryption:
    provider: sops
    secretRef:
      name: sops-key