creation_rules:
  - path_regex: talos/.*.yaml
    encrypted_regex: ^(data|stringData|crt|secret|id|token|key|secretboxEncryptionSecret|bootstraptoken|secretboxencryptionsecret)$
    age: age16khheln7aqhe8atf8ggxvykdqspsqpwgq5yw3y7l9zn8ezf2zausll77wa
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    age: age16khheln7aqhe8atf8ggxvykdqspsqpwgq5yw3y7l9zn8ezf2zausll77wa
  - path_regex: .*.talosconfig
    age: age16khheln7aqhe8atf8ggxvykdqspsqpwgq5yw3y7l9zn8ezf2zausll77wa
