# https://taskfile.dev

version: '3'

tasks:
  fluxinit:
    desc: Bootstrap Flux for cluster
    cmds:
      - flux bootstrap github --token-auth --owner=nitespacedev --repository=home-k8s-lab --branch=main --path=clusters/opilab
