---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: ">=1.18.0 <=1.19.0"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
      interval: 1m
  values:
    crds:
      enabled: true
    podDnsConfig:
      nameservers:
        - "1.1.1.1"
        - "9.9.9.9"
    dns01RecursiveNameservers: "1.1.1.1:53"