---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      chartRef:
        kind: OCIRepository
        name: cert-manager
        namespace: traefik
      interval: 1m
  values:
    crds:
      enabled: true