---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager
  namespace: traefik
spec:
  interval: 5m0s
  url: https://traefik.github.io/charts
  ref:
    tag: v1.18.1