---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dns-local
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: ">=1.17.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: traefik
      interval: 1m
  values:
    domainFilters:
      - nite.name
    sources:
      - service
      - ingress
      - traefik-proxy
    provider:
      name: rfc2136
    extraArgs:
      - --rfc2136-host=192.168.4.140
      - --rfc2136-port=53
      - --rfc2136-zone=nite.name
      - --rfc2136-tsig-secret-alg=hmac-sha256
      - --rfc2136-tsig-keyname=external-dns
      - --rfc2136-tsig-axfr
    env:
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: tsig-key
            key: key 