---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-cloudflare-tunnel
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudflare-tunnel
      sourceRef:
        kind: HelmRepository
        name: cloudflare-repo
        namespace: traefik
      interval: 1m
  values:
    cloudflared:
      tunnelSecret: cf-tunnel-credentials
      secretName: cf-tunnel-credentials
      tunnelId: 5196f111-e3f4-44f0-bbb1-c2da7015f9af
    ingress:
      - service: traefik-cloudflare