---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-lan
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: ">=3.5 <=3.6"
      sourceRef:
        kind: HelmRepository
        name: traefik-repo
        namespace: traefik
      interval: 1m
  values:
    providers:
      kubernetesCRD:
        enabled: true
        allowExternalNameServices: true
        allowCrossNamespaces: true
        ingressClass: traefik-lan
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true
    ports:
      web:
        port: 80
        nodePort: 30000
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        port: 443
        nodePort: 30001
    api:
      dashboard: true
      insecure: true
    gateway:
      listeners:
        web:
          port: 80
          protocol: HTTP
          namespacePolicy:
            from: All
        websecure:
          port: 443
          protocol: HTTPS
          namespacePolicy:
            from: All
          mode: Terminate
    service:
      enabled: true
      type: LoadBalancer
      annotations: {}
      labels: { color: green }