apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: config-map-readers-ubuntu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-map-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:node:pilab1