apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-map-reader
rules:
- apiGroups:
  - ''
  resourceNames:
  - worker-config-ubuntu
  resources:
  - configmaps
  verbs:
  - get
  - list