---
clusterName: opilab
endpoint: https://192.168.4.114:6443
talosVersion: 1.11.0
allowSchedulingOnMasters: true
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12

cniConfig:
  name: none

patches:
  - |-
    cluster:
      proxy:
        disabled: true


nodes:
  - hostname: ohm-talos
    controlPlane: true
    ipAddress: 192.168.5.10
    installDisk: /dev/vda
    nodeConfigs:
      machineSpec:
        mode: metal
        arch: arm64
  - hostname: olabsumuvm
    controlPlane: false
    ipAddress: 192.168.5.15
    installDisk: /dev/sda
  - hostname: olabtsuvm
    controlPlane: false
    ipAddress: 192.168.5.16
    installDisk: /dev/sda
  - hostname: kitchen
    controlPlane: false
    ipAddress: 192.168.5.19
    installDisk: /dev/sda

controlPlane:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
          - siderolabs/nfsd
          - siderolabs/nvme-cli
          - siderolabs/qemu-guest-agent
          - siderolabs/util-linux-tools
  patches:
    - |-
      - op: add
        path: /machine/network/nameservers
        value:
          - 192.168.4.205
          - 192.168.4.181
            #      - op: add
            #        path: /machine/kubelet/extraArgs
            #        value:
            #          rotate-server-certificates: "true"
            #
worker:
  patches:
    - |-
      - op: add
        path: /machine/network/nameservers
        value:
          - 192.168.4.205
          - 192.168.4.181
