# https://taskfile.dev

version: '3'

includes:
  nodes:
    taskfile: ./tasks
    flatten: true

tasks:
  gen:
    desc: Gen config files for all nodes
    sources:
      - talconfig.yaml
    generates:
      - opilab/*yaml
    cmds:
      - talhelper genconfig -o opilab
    silent: true

  bootstrap:
    desc: Bootstrap Talos
    run: once
    silent: false
    cmds:
      - talosctl bootstrap -n 192.168.4.114


  initnodes:
    desc: Initialize nodes
    run: once
    deps:
      - gen
    cmds:
      - task: init:all

  update:
    desc: Apply updated config to nodes
    run: once
    silent: false
    deps:
      - gen
    cmds:
      - task: update:all

  netsetup:
    desc: Initialize Cilium on a new cluster
    run: once
    silent: false
    cmds:
      - helm repo add cilium https://helm.cilium.io/
      - helm install cilium cilium/cilium --version 1.18.1 --namespace kube-system --values ../network/cilium/values.yaml
