apiVersion: v1
kind: Service
metadata:
  name: hubble-ui-svc
  labels:
    color: green
spec:
  selector:
    app: hubble-ui
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80