apiVersion: v1
kind: Service
metadata:
  name: hubble-ui-svc
  annotations:
    external-dns.alpha.kubernetes.io/hostname: opihubble.nite.name
  labels:
    color: green
spec:
  selector:
    k8s-app: hubble-ui
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081